### Site info:
title: 秒速3オクターブ
tagline: 
author: Kanoe
email: kanoe@sampele.jp
description: "音楽したりプログラミングしたり..."
keywords: "DTM, Mac, プログラミング, ゲーム, 音楽"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kanoe.studio/" # the base hostname & protocol for your site
locale: ja_JP

### Personal info and site tools info:
twitter_username: KanoeTweet
github_username:  KanoeGitHub
disqus_shortname: 
favicon:     "/images/favicon.ico"
aboutme: Hello  # these are shown on aboutme-sidebar.
aboutme_photo: https://s3-ap-northeast-1.amazonaws.com/creofuga3/images/artworks/155331/default.155331.png?1542977316# your photo.
google_analytics_key: # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "jp" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: "サイト内検索"
      Home: "ホーム"
      About: "About"
      Guestbook: "メッセージ"
      Subscribe: "購読"


### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Kanoeroom
        href: http://blog.kanoe.studio/
        title: Another Jekyll blog theme
      - name: author's website
        href: https://KanoeStudio
        title: Kanoe Studio


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
